VR-5278 CLI: verta registry create registeredmodelversion
VertaAI/modeldb pull request #1073
Opened 2020-07-21 00:13 UTC by nhatsmrt

Separate https://github.com/VertaAI/modeldb/pull/1067 from CLI stuff

2020-07-21 00:33 UTC, convoliution requested changes

2020-07-21 00:33 UTC, convoliution commented on client/verta/verta/_cli/registry/create.py
> +            model_version.log_artifact(key, path, True)
See https://github.com/VertaAI/modeldb/pull/1075#discussion_r457766819

2020-07-21 01:30 UTC, nhatsmrt commented on client/verta/verta/_cli/registry/create.py
> +            model_version.log_artifact(key, path, True)
Fixed.

2020-07-22 03:39 UTC, convoliution approved these changes

2020-07-22 03:41 UTC, merged