VR-5577 Remove support for client.get_reg_mod_ver() by name
VertaAI/modeldb pull request #1182
Opened 2020-07-30 20:36 UTC by nhatsmrt

2020-07-31 00:20 UTC, convoliution requested changes

2020-07-31 00:20 UTC, convoliution commented on client/verta/tests/conftest.py
> +    created_registered_models.append(registered_model)
It might be less verbose if we call `utils.delete_registered_model()` at the end of the `registered_model` fixture, and only use `created_registered_models` in tests where we create _additional_ models.

Actually, if we did that then we might not need to change any of the test code, since `registered_model` would clean itself up basically like it used to. What do you think?

2020-07-31 00:22 UTC, convoliution commented
fyi @evgeniilezhnin: removing Client's get model version by name (from now on, ID only 🔥).
This means we're also removing RegisteredModel from Context.

2020-07-31 01:46 UTC, nhatsmrt commented on client/verta/tests/conftest.py
> +    created_registered_models.append(registered_model)
That is actually a great idea. Done.

2020-07-31 04:25 UTC, evgeniilezhnin approved these changes

2020-08-02 18:34 UTC, convoliution approved these changes

2020-08-02 18:35 UTC, merged