NPE while access background task count before it registered
VertaAI/modeldb pull request #1205
Opened 2020-08-03 12:11 UTC by ad-47

2020-08-03 16:54 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) == null) {
```suggestion
     if (System.getProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT) == null) { 
```

2020-08-03 16:56 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +    if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
```suggestion
    if (System.getProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
```

2020-08-03 16:56 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +    if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
```suggestion
    if (System.getProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
```

2020-08-03 16:58 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +          System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT));
```suggestion
          System.getProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT));
```

2020-08-03 17:02 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +        System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
```suggestion
        System.setProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT, "0");
```

2020-08-03 17:02 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
```suggestion
      System.setProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT, "0");
```

2020-08-03 17:03 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +          (int) System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT);
```suggestion
          (int) System.getPropertyModelDBConstants.BACKGROUND_UTILS_COUNT);
```

2020-08-03 17:04 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
```suggestion
      System.setProperty(ModelDBConstants.BACKGROUND_UTILS_COUNT, "0");
```

2020-08-03 17:06 UTC, ravishetye requested changes
this can have improvements. Please check the changes.
To resolve the NPE I will update add a try-catch in a different PR.

2020-08-04 05:39 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) == null) {
Fixed

2020-08-04 05:39 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +    if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
Fixed

2020-08-04 05:39 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +    if (System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT) != null) {
Fixed

2020-08-04 05:40 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +          System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT));
Fixed

2020-08-04 05:40 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +        System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
Fixed

2020-08-04 05:40 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
Fixed

2020-08-04 05:40 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +          (int) System.getProperties().get(ModelDBConstants.BACKGROUND_UTILS_COUNT);
Fixed

2020-08-04 05:40 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/utils/ModelDBUtils.java
> +      System.getProperties().put(ModelDBConstants.BACKGROUND_UTILS_COUNT, 0);
Fixed

2020-08-04 06:39 UTC, ravishetye approved these changes

2020-08-04 06:40 UTC, merged