VR-5587 Enable Dataset tags CRUD
VertaAI/modeldb pull request #1206
Opened 2020-08-03 15:37 UTC by nhatsmrt

Requires _update from https://github.com/VertaAI/modeldb/pull/1197/

2020-08-04 22:09 UTC, convoliution requested changes
Small docstring request

2020-08-04 22:09 UTC, convoliution commented on client/verta/verta/_dataset_versioning/dataset.py
> +        Deletes a tag from this dataset
```suggestion
        Deletes a tag from this Dataset.
```

2020-08-04 22:28 UTC, nhatsmrt commented on client/verta/verta/_dataset_versioning/dataset.py
> +        Deletes a tag from this dataset
Fixed.

2020-08-04 22:28 UTC, nhatsmrt commented
Conflict resolved.

2020-08-05 15:18 UTC, convoliution approved these changes

2020-08-05 15:18 UTC, merged