VR-5936 Add brief examples to Strategy, Resource, Metric, and Rule docstrings
VertaAI/modeldb pull request #1315
Opened 2020-08-15 02:13 UTC by nhatsmrt

@convoliution See if the example makes sense.
Also fix some small mix-up in docstrings for autoscaling metrics 😰

2020-08-18 02:28 UTC, convoliution requested changes

2020-08-18 02:28 UTC, convoliution commented on client/verta/verta/deployment/resources.py
> +        cpu = CpuMillis(128)
1000 millis = 1 CPU core, so a nice fraction of 1000 like `250` makes more sense than `128`.
```suggestion
        cpu = CpuMillis(250)
```

2020-08-18 02:28 UTC, convoliution commented on client/verta/verta/deployment/update/_strategies.py
> +
Could you also do me a favor and move the **Parameters** from the init docstring into this class docstring (and then remove the init docstring)? See [`Client`](https://github.com/VertaAI/modeldb/blob/master/client/verta/verta/client.py) for what that would look like.

2020-08-18 04:31 UTC, nhatsmrt commented on client/verta/verta/deployment/update/_strategies.py
> +
Done.

2020-08-18 04:31 UTC, nhatsmrt commented on client/verta/verta/deployment/resources.py
> +        cpu = CpuMillis(128)
Fixed.

2020-08-20 15:33 UTC, convoliution approved these changes

2020-08-20 15:37 UTC, merged