Remove validation check for / from repo names to Service
VertaAI/modeldb pull request #1533
Opened 2020-09-22 13:33 UTC by ad-47

**Jira Ticket:** https://vertaai.atlassian.net/browse/VR-6616

2020-09-23 03:04 UTC, ravishetye requested changes
The idea was to allow : and / in dataset names and not allow them for repositories.
there is no requirement for allowing just :

2020-09-23 04:09 UTC, ad-47 commented
Yes. I have done it at https://github.com/VertaAI/modeldb/pull/1533/files#diff-0c4fc28beb0966f19527f12aa5cc790eR392. I have added just `:` colon check for the branch name allow the `/` but the branch name should not allow the `:` so https://github.com/VertaAI/modeldb/pull/1533/files#diff-678c1a74bf0f4a56c36bdfba5112c87eR722-R726 logic modified for branch name.

2020-09-23 06:13 UTC, ad-47 commented
Moved validation check to service level

2020-09-24 02:48 UTC, ravishetye approved these changes

2020-09-24 02:50 UTC, merged