Fix experiment service as per new audit log design
VertaAI/modeldb pull request #1956
Opened 2021-02-11 09:19 UTC by ad-47

2021-02-15 19:24 UTC, conradoverta requested changes

2021-02-15 19:24 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experiment/ExperimentServiceImpl.java
> +      Long workspaceId) {
Same comment from dataset version.

2021-02-19 12:00 UTC, evgeniilezhnin commented
deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)

2021-02-24 04:58 UTC, conradoverta commented
> deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)

Not sure why this is relevant. Could you expand?

2021-02-25 09:33 UTC, evgeniilezhnin commented
> > deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)
> 
> Not sure why this is relevant. Could you expand?

because you can't save entity with workspace id = 0 in Audit Log Service. There is a validation that it shouldn't be 0

2021-02-25 09:36 UTC, evgeniilezhnin commented
> > > deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)
> > 
> > 
> > Not sure why this is relevant. Could you expand?
> 
> because you can't save entity with workspace id = 0 in Audit Log Service. There is a validation that it shouldn't be 0

it's the same thing as in your comment: https://github.com/VertaAI/modeldb/pull/1959#discussion_r576386747

2021-03-09 01:58 UTC, conradoverta commented
> > > > deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)
> > > 
> > > 
> > > Not sure why this is relevant. Could you expand?
> > 
> > 
> > because you can't save entity with workspace id = 0 in Audit Log Service. There is a validation that it shouldn't be 0
> 
> it's the same thing as in your comment: [#1959 (comment)](https://github.com/VertaAI/modeldb/pull/1959#discussion_r576386747)

So you mean it was fixed in the same PR?

2021-03-09 08:47 UTC, evgeniilezhnin commented
> > > > > deleteExperiment doesn't use workspace id (ExperimentServiceImpl.java:905)
> > > > 
> > > > 
> > > > Not sure why this is relevant. Could you expand?
> > > 
> > > 
> > > because you can't save entity with workspace id = 0 in Audit Log Service. There is a validation that it shouldn't be 0
> > 
> > 
> > it's the same thing as in your comment: [#1959 (comment)](https://github.com/VertaAI/modeldb/pull/1959#discussion_r576386747)
> 
> So you mean it was fixed in the same PR?

I just mean that this PR is about adding workspace id to save audit log, but in deleteExperiment save audit log still doesn't have workspace id

2021-03-09 09:15 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/experiment/ExperimentServiceImpl.java
> +      Long workspaceId) {
it is resolved

2021-03-09 09:18 UTC, ad-47 commented
I am sorry i have merge PRs which has this PR as a base PR. now this PR has more code. :(

2021-03-09 19:25 UTC, conradoverta approved these changes

2021-03-12 08:03 UTC, merged