Fix experiment run service as per new audit log design
VertaAI/modeldb pull request #1957
Opened 2021-02-11 10:36 UTC by ad-47

2021-02-15 19:25 UTC, conradoverta approved these changes

2021-02-15 19:25 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experimentRun/ExperimentRunServiceImpl.java
> +      Long workspaceId) {
Same comment from dataset version.

2021-02-15 19:28 UTC, conradoverta requested changes
Pressed the wrong button

2021-02-20 04:37 UTC, evgeniilezhnin commented on backend/src/main/java/ai/verta/modeldb/experimentRun/ExperimentRunServiceImpl.java
> +      Long workspaceId) {
https://github.com/VertaAI/modeldb/pull/1979

2021-02-24 04:46 UTC, conradoverta approved these changes

2021-02-24 04:48 UTC, conradoverta requested changes

2021-02-24 04:48 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experimentRun/ExperimentRunServiceImpl.java
> +                        workspaceId))
Anti-pattern?

2021-02-24 04:48 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experimentRun/ExperimentRunServiceImpl.java
> +            entry.getValue());
Multiple log entries. It has to be one per request.

2021-03-09 01:57 UTC, conradoverta approved these changes

2021-03-09 09:11 UTC, merged