Add support for model metadata
VertaAI/modeldb pull request #204
Opened 2017-02-24 01:41 UTC by mcslao

2017-02-24 15:30 UTC, mpvartak requested changes

2017-02-24 15:30 UTC, mpvartak commented on client/python/samples/basic/JsonSample.json
> +      "extra-kv-pair": 2,
Change name?

2017-02-24 15:30 UTC, mpvartak commented on client/python/samples/basic/YamlSample.yaml
> +---
Remove

2017-02-24 15:30 UTC, mpvartak commented on frontend/public/js/m.js
> +          console.log("Printing model metadata...");
Add comment to remove this after @weienlee's change is in.

2017-02-24 15:30 UTC, mpvartak commented on frontend/routes/projects.js
> +    console.log(response);
extraneous

2017-02-24 15:30 UTC, mpvartak commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file needs to go. From other branch.

2017-02-28 22:32 UTC, arubisov commented
This doesn't go so smoothly... gen_sqlite ran fine and mongod fired up. Running start_server.sh dumped out a bunch of errors:

✓ arubisov@lvappi01089 ~/modeldb/server $ ./start_server.sh
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for edu.mit.csail.db.ml:modeldb:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 93, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building modeldb 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ modeldb ---
[INFO] Deleting /home/arubisov/modeldb/server/target
[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ modeldb ---
[debug] execute contextualize
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ modeldb ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 143 source files to /home/arubisov/modeldb/server/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/util/ExceptionWrapper.java:[4,14] error: package modeldb does not exist
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/storage/PipelineEventDao.java:[5,0] error: package modeldb does not exist
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/storage/PipelineEventDao.java:[32,78] error: cannot find symbol
[ERROR]  class PipelineEventDao
/home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/storage/PipelineEventDao.java:[32,21] error: cannot find symbol
[ERROR]  class PipelineEventDao
/home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/storage/PipelineEventDao.java:[47,44] error: cannot find symbol
[ERROR]  class PipelineEventDao
/home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/storage/PipelineEventDao.java:[47,16] error: cannot find symbol
[ERROR]  class PipelineEventDao
/home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/algorithm/similarity/SimilarModels.java:[7,14] error: package modeldb does not exist
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/algorithm/similarity/SimilarModels.java:[8,14] error: package modeldb does not exist
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/algorithm/similarity/SimilarModels.java:[9,14] error: package modeldb does not exist
[ERROR] /home/arubisov/modeldb/server/src/main/java/edu/mit/csail/db/ml/server/algorithm/similarity/SimilarModels.java:[29,57] error: cannot find symbol
[ERROR]  class SimilarModels
...etc

2017-02-28 23:49 UTC, mpvartak commented
Hi @arubisov,

This has to do with the thrift version (it can't find modeldb package). Note that the build process has changed slightly. If your thrift version is x.y.z, you would run ./start_server.sh x.y.z

This will fix the error.

Manasi

2017-02-28 23:50 UTC, mpvartak approved these changes

2017-03-01 06:52 UTC, geffy commented on client/python/modeldb/basic/ModelDbSyncerBase.py
> +            if metadata_constants.DATASET_METADATA_KEY in dataset_dict else {}
Can be done shortly: `dataset_dict.get(metadata_constants.DATASET_METADATA_KEY, {})`

2017-03-04 04:18 UTC, mpvartak commented on client/python/modeldb/basic/ModelDbSyncerBase.py
> +            if metadata_constants.DATASET_METADATA_KEY in dataset_dict else {}
great, fixed!

2017-03-04 04:35 UTC, merged