fix config example
VertaAI/modeldb pull request #2052
Opened 2021-03-24 07:20 UTC by evgeniilezhnin

2021-03-26 11:12 UTC, ad-47 approved these changes

2021-03-26 11:15 UTC, ad-47 commented on backend/config.example.yaml
> +  protocol: http
there is one missing field in config here : `enabled`,

2021-03-26 11:17 UTC, ad-47 commented on backend/config.example.yaml
> +  protocol: http
there are many other fields are missing in config file like in s3 config `minioEndpoint:` is missing etc. need to verify entire config file.

2021-03-26 11:17 UTC, ad-47 requested changes
Needs to be check whole config file for missing parameters

2021-07-28 03:42 UTC, conradoverta commented
Is this still relevant?

2021-07-28 12:02 UTC, evgeniilezhnin commented
> Is this still relevant?

yes, but I forgot to add other missing fields, sorry

2021-08-11 10:46 UTC, ad-47 approved these changes

2021-08-11 11:23 UTC, evgeniilezhnin commented
Anands changes LGTM

2021-08-11 11:23 UTC, merged