Remove TODO for feature in ER creation
VertaAI/modeldb pull request #2169
Opened 2021-04-18 12:18 UTC by ad-47

2021-04-18 20:48 UTC, conradoverta requested changes
Are features like tags?

2021-04-18 20:48 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experimentRun/FutureExperimentRunDAO.java
> +            executor)
Same feedback as main PR

2021-04-19 15:35 UTC, ad-47 commented
> Are features like tags?

Yes it is.

2021-04-19 15:43 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/experimentRun/FutureExperimentRunDAO.java
> +            executor)
Fixed

2021-04-19 20:28 UTC, conradoverta approved these changes

2021-04-20 07:56 UTC, merged