Revamp readme
VertaAI/modeldb pull request #217
Opened 2017-03-08 19:05 UTC by mcslao

2017-03-09 15:17 UTC, mpvartak commented on README.md
> +- [spark.ml](client/scala/libs/spark.ml)
Link to: https://github.com/mitdbg/modeldb/blob/master/docs/getting_started/spark_ml.md

Also, can you update this file to remove the installation steps and only keep the workflow updates?

2017-03-09 15:30 UTC, mpvartak requested changes
The README updates look really good overall! I have a few specific comments and one relatively big one, which is to pull out the Light API more explicitly in the root README and then have a separate README showing how to use it in a workflow. I've added more specific comments in the review.

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +- [spark.ml](client/scala/libs/spark.ml)
Can you link to https://github.com/mitdbg/modeldb/blob/master/docs/getting_started/spark_ml.md?

Also please remove the installation instructions on that page and only keep the workflow ones

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +- [others](client/python/samples/basic)
This should link to the Light API read me as opposed to samples

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +**See the ModelDB frontend in action**: [Watch the video](https://youtu.be/m2PhgEkx8-E)
Please embed video

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +<img src="docs/getting_started/images/frontend-1.png" width="90%"><br>
Please resize to be smaller

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +<img src="docs/getting_started/images/frontend-2.png" width="90%"><br>
Also label figs

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +ModelDB **works with any machine learning workflow** with ModelDB's Light API. Model metrics and metadata can be synced by calling a few functions just like in [this sample basic workflow](client/pyt
Pull out supported environments more explicitly and at the top level. E.g. "All environments via Light API, advanced support for sklearn and spark.ml"

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +    ```
put pip install -r here

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +
put pip install here

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +    ./gen_sqlite.sh
Add a BOLD warning that this should be done only once. that this will clean out any data in the DB

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +    # start mongodb
Reword to say "make sure mongodb is running"

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +Contributions are also welcome! Please read [this](CONTRIBUTING.md) to get started.
Add a section called "Contributing"

2017-03-09 15:30 UTC, mpvartak commented on README.md
> +2. **Run your models.**
fix to say something like "instrumented with ModelDB as shown in step blah"

2017-03-09 15:30 UTC, mpvartak commented on client/python/README.md
> +This is the Python client for ModelDB, which includes ModelDB's Light API and the [scikit-learn](http://scikit-learn.org/stable) client.
[MAJOR] I think we should make the Light API and sklearn into two separate READMEs. These are two v. diff code paths that support diff functionality. Having them together will confuse people.

So let's make a separate read me for LIGHT. You can say that it's written in Python of course.

2017-03-09 15:32 UTC, mpvartak commented on client/python/README.md
> +Tthe Light API is a way for users to incorporate any ML workflow with ModelDB, while the scikit-learn library is responsible for storing machine learning operations in scikit-learn,
Spelling

2017-03-09 17:30 UTC, mcslao commented on README.md
> +**See the ModelDB frontend in action**: [Watch the video](https://youtu.be/m2PhgEkx8-E)
I don't think it's possible to embed videos. I can only make a preview image appear which when clicked will still lead users to Youtube and not play the video within the readme.

2017-03-10 05:52 UTC, mpvartak commented
Looks good.

2017-03-10 05:52 UTC, mpvartak approved these changes

2017-03-10 05:52 UTC, merged