Mv/artifact path fix
VertaAI/modeldb pull request #2439
Opened 2021-06-23 15:21 UTC by mvartakAtVerta

Various fixes for log_artifacts for windows

2021-06-30 05:26 UTC, mvartakAtVerta commented
Lots of fixes for tests on Windows. Known issues:
1) test_versioning/test_dataset.py::TestPath needs revisiting for path comparisons on windows
2) test_creation_updates_dataset_timestamp shows failures on windows and unix
3) TestPathManagedVersioning.test_mngd_ver_folder shows failure on windows

2021-06-30 16:48 UTC, convoliution requested changes
I need to do some more reading on the Windows's specific changes here. In broad strokes, for this initial review:

1. I'm not personally familiar with `pip list --format freeze`! Is it functionally different from `pip freeze`? I'm going to spend some time after this initial review to look into it.
2. I wonder if `os.path.relpath(path, base_path).replace("\\", "/")` needs to be done in other parts of the client code as well. I'm curious about the exact nature of why Windows is doing this!
3. The use of `delete=False` may lead to leftover files on the system, if the tempfiles aren't cleaned up. This may need a bigger solution.

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/conftest.py
> +        "/".join([strs[5]]),
This seems odd to me—these are filepaths on the local machine, so I'd expect `os.path.join()` to be appropriate here.

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/conftest.py
> +    with tempfile.NamedTemporaryFile("w+", delete=False) as tempf:
Suggestion:

- `delete=False` is 👌, though a bit odd to me
- line 526: move `yield tempf` out of the `with:` block (unindent one level)'
- after the `yield`, add an `os.remove(tempf.name)`

With this, we can take out some of the `.close()`s and `os.remove(tempf.name)`s added to tests in this PR

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/test_versioning/test_environment.py
> +    with tempfile.NamedTemporaryFile("w+", delete=False) as tempf:
See my suggestion on `requirements_file()` in conftest.py

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/test_versioning/test_environment.py
> +    with tempfile.NamedTemporaryFile("w+", delete=False) as tempf:
See my suggestion on `requirements_file()` in conftest.py

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/test_deployment.py
> +        experiment_run.log_artifact(key, tempf.name)
I suspect that for all of these, we could leave the `with:` block intact but simply move the `log_artifact() call out of it (unindent that one line, one level)

2021-06-30 16:48 UTC, convoliution commented on client/verta/tests/test_versioning/test_dataset.py
> +            os.path.relpath(path, base_path).replace("\\", "/")
I'm reading more about this, and it sounds bananas.

I'm pretty sure our client uses `relpath()` in a few places, and I'm concerned that this is a wider underlying problem.

2022-09-30 18:59 UTC, liuverta commented
I remember having difficulty picking up this PR when it was opened, and now with the numerous merge conflicts I fear it is no longer in a good state.

But make no mistake, Windows: I'm not afraid of you. One day...

2022-09-30 18:59 UTC, closed without merging