Pass through extra headers on every request.
VertaAI/modeldb pull request #2510
Opened 2021-07-23 20:14 UTC by lsb

2021-07-23 20:14 UTC, lsb commented
Some manual testing:

```
>>> Client(host="scribd.external.verta.ai", email="leeb@scribd.com", dev_key="12341234-1234-1234-1234-123412341234")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leeb/modeldb/client/verta/verta/client.py", line 199, in __init__
    _utils.raise_for_http_error(response)
  File "/Users/leeb/modeldb/client/verta/verta/_internal_utils/_utils.py", line 681, in raise_for_http_error
    six.raise_from(requests.HTTPError(message, response=response), None)
  File "<string>", line 3, in raise_from
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://scribd.external.verta.ai/api/v1/modeldb/project/verifyConnection at 2021-07-23 20:03:21.724000 UTC
>>> Client(host="scribd.external.verta.ai", email="leeb@scribd.com", dev_key="12341234-1234-1234-1234-123412341234", extra_auth_headers={"X-GH-Access-Token": "12341234-1234-1234-1234-123412341234"})
connection successfully established
<verta.client.Client object at 0x10b373670>
```

2021-07-23 23:52 UTC, convoliution requested changes

2021-07-23 23:52 UTC, convoliution commented on client/verta/verta/client.py
> +        auth = {**extra_auth_headers, _utils._GRPC_PREFIX+'source': "PythonClient"}
Thank you for the contribution @lsb!

Unpacking inside a `dict` literal is unfortunately a syntax error in Python 2, which we'd like to maintain support for where possible; I believe this alternative should work:
```suggestion
        auth = extra_auth_headers.copy()
        auth.update({_utils._GRPC_PREFIX+'source': "PythonClient"})
```

2021-07-24 19:24 UTC, convoliution approved these changes
Nice, thanks again @lsb 

I'll have this merged come Monday and start running it through our tests.

2021-07-27 00:29 UTC, merged