Add back ports so docker-compose up succeeds
VertaAI/modeldb pull request #261
Opened 2017-08-25 03:44 UTC by zitterbewegung

If you don't add jessie back ports mongodb-org-shell will not install due to the fact its looking for libssl1.0 which isn't installable.

2017-08-25 13:34 UTC, justinanderson requested changes
Thanks for the PR, @zitterbewegung. Could you make a couple changes before I merge it?

1. Combine the RUN command you added with the one after it, to minimize the number of layers this Dockerfile creates.

2. Update the mongodb source entry to use the xenial version, since openjdk:8 changed its base image from jessie to stretch. `echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.4.list`.

2017-08-25 13:43 UTC, zitterbewegung commented
All right will do I’ll try to get this done over the weekend

2017-08-25 19:41 UTC, zitterbewegung commented
I have made the changes you requested.

2017-08-26 19:26 UTC, zitterbewegung reviewed
Hi this commit has the changes you wanted.

2017-08-28 18:23 UTC, justinanderson commented on dockerbuild/Dockerfile-backend
> +    /etc/apt/sources.list.d/backports.list &&
@zitterbewegung Needs a trailing \ here and the next line. Once that's fixed, this PR will be good to merge.

2017-08-30 16:37 UTC, zitterbewegung commented
Hi, I added trailing slashes like you wanted.

2017-08-30 19:56 UTC, justinanderson approved these changes

2017-08-30 20:03 UTC, merged

2017-08-30 20:03 UTC, justinanderson commented
Merged. Thanks for the PR, @zitterbewegung!