project events implementation with feature flag
VertaAI/modeldb pull request #2693
Opened 2021-10-27 09:05 UTC by ad-47

## Impact and Context

## Risks and Area of Effect

## Testing

## How to Revert

2021-10-27 15:29 UTC, conradoverta requested changes

2021-10-27 15:29 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/project/ProjectServiceImpl.java
>                  Optional.of(projectId), Optional.empty(), ModelDBServiceResourceTypes.PROJECT);
Should we even be making this call to uac if it's disabled? Let's review to make sure we're not doing unnecessary calls.

2021-10-28 04:32 UTC, anandjakhaniya commented on backend/src/main/java/ai/verta/modeldb/project/ProjectServiceImpl.java
>                  Optional.of(projectId), Optional.empty(), ModelDBServiceResourceTypes.PROJECT);
nice catch, i missed that place :)

2021-10-28 04:41 UTC, anandjakhaniya commented on backend/src/main/java/ai/verta/modeldb/project/ProjectServiceImpl.java
>                  Optional.of(projectId), Optional.empty(), ModelDBServiceResourceTypes.PROJECT);
line was unused and forgot to remove it. so removed it now.

2021-11-08 15:55 UTC, conradoverta approved these changes

2021-11-08 15:56 UTC, merged