Migrated UpdateExperimentName endpoint from hibernate to jdbi Impl
VertaAI/modeldb pull request #2848
Opened 2022-02-11 08:31 UTC by ad-47

## Impact and Context

## Risks and Area of Effect

## Testing

## How to Revert

2022-02-12 21:24 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentDAO.java
> +                  request.getId(), "name", ModelDBUtils.checkEntityNameLength(name));
Names cannot be duplicated. We're not checking that.

2022-02-12 21:24 UTC, conradoverta requested changes

2022-02-12 21:24 UTC, conradoverta commented on backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentDAO.java
> +                  request.getId(), "name", ModelDBUtils.checkEntityNameLength(name));
Names cannot be duplicated. We're not checking that.

2022-02-16 12:29 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentDAO.java
> +                  request.getId(), "name", ModelDBUtils.checkEntityNameLength(name));
We are not checking duplication for Experiment entity. We were not checking duplication on old code as well. reference: https://github.com/VertaAI/modeldb/blob/daf936ab83230ea4565fd3f3e047e1d83a1b03b5/backend/src/main/java/ai/verta/modeldb/experiment/ExperimentDAORdbImpl.java#L230

2022-02-17 07:16 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/experiment/FutureExperimentDAO.java
> +                  request.getId(), "name", ModelDBUtils.checkEntityNameLength(name));
Added check for experiment name already exists in project or not

2022-02-17 18:35 UTC, liam-verta commented on backend/src/test/java/ai/verta/modeldb/ExperimentTest.java
> +      LOGGER.warn("Error Code : " + status.getCode() + " Description : " + status.getDescription());
This error is expected as part of the test. Info at most. 
```suggestion
      LOGGER.info("Error Code : " + status.getCode() + " Description : " + status.getDescription());
```

2022-02-17 19:08 UTC, liam-verta approved these changes

2022-02-21 10:33 UTC, merged