Docs: fix footer bug
VertaAI/modeldb pull request #381
Opened 2020-03-19 19:46 UTC by AndreyKuznetsovQS

2020-03-19 19:58 UTC, convoliution requested changes
I see this fixes the bug for long pages, but now the footer is in the middle of the window on short pages:
<img width="1440" alt="Screen Shot 2020-03-19 at 12 57 30 PM" src="https://user-images.githubusercontent.com/7754936/77109524-4b4b3700-69e1-11ea-8b4f-b8cfe7904d29.png">

2020-03-20 12:43 UTC, AndreyKuznetsovQS commented
> I see this fixes the bug for long pages, but now the footer is in the middle of the window on short pages:
> <img alt="Screen Shot 2020-03-19 at 12 57 30 PM" width="1440" src="https://user-images.githubusercontent.com/7754936/77109524-4b4b3700-69e1-11ea-8b4f-b8cfe7904d29.png">

I have tried to fix it. @convoliution please check it.

2020-03-20 17:20 UTC, convoliution commented
It's still there 😧  (I'm certain I'm on the correct latest commit)
<img width="1440" alt="Screen Shot 2020-03-20 at 10 18 56 AM" src="https://user-images.githubusercontent.com/7754936/77189081-3d0a2300-6a94-11ea-9988-07dfa65f47c9.png">

2020-03-20 18:07 UTC, convoliution commented on client/verta/docs/_static/custom.css
> +  min-height: 100%;
This solves the problem for me in Firefox & Safari,
though I'm not sure what the best practice is regarding `vh` vs `%`.
```suggestion
  min-height: 100vh;
```

2020-03-23 05:39 UTC, AndreyKuznetsovQS commented
> It's still there 😧 (I'm certain I'm on the correct latest commit)
> <img alt="Screen Shot 2020-03-20 at 10 18 56 AM" width="1440" src="https://user-images.githubusercontent.com/7754936/77189081-3d0a2300-6a94-11ea-9988-07dfa65f47c9.png">

@convoliution I added your suggestion and some changes. Please check it on your machine.

2020-03-23 16:03 UTC, convoliution approved these changes
I have verified this works in both Firefox and Safari. I will go ahead and merge this. Thank you Andrey 😭

2020-03-23 16:03 UTC, merged