fix merge logic
VertaAI/modeldb pull request #411
Opened 2020-03-24 07:30 UTC by ad-47

2020-03-24 07:33 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/versioning/BlobDAORdbImpl.java
> +    }
formatting

2020-03-24 07:33 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/versioning/BlobDAORdbImpl.java
> +                LinkedHashMap::new));
auto formatting

2020-03-26 04:27 UTC, ravishetye commented
I resolved the issue by breaking the session into read and write. So this PR is not required. However if there are any other changes which we should not throw away please file a separate PR.

2020-03-26 04:28 UTC, ravishetye requested changes
not needed

2020-03-27 09:11 UTC, closed without merging