VR-3946 validation and exception message fix
VertaAI/modeldb pull request #513
Opened 2020-04-14 06:28 UTC by evgeniilezhnin

2020-04-14 23:09 UTC, ravishetye approved these changes

2020-04-14 23:18 UTC, ravishetye requested changes
when I said notebook I meant this can be reproduce in the standard notebook: https://github.com/VertaAI/modeldb/blob/master/demos/webinar-2020-4-1/census-s3-oss-versioning.ipynb

Based on your fix we will throw an invalid argument error, I am not sure if making the python and requirement version compulsory is the right fix for this.

tagging @conradoverta  and @convoliution since they will have more context on python requirements

2020-04-15 00:14 UTC, convoliution commented
I do not think the backend should raise an error. I believe that fields should be optional from the backend's perspective if things are simply being logged. But I could be wrong about that, so I'd defer to @conradoverta.

@ravishetye This error is surprising to me, since I would have expected the Client to always capture the versions (especially looking at the webinar notebook). Do you have any other details about how you were running it?

2020-04-15 07:27 UTC, evgeniilezhnin commented
removed validation, added null checked

2020-04-16 03:52 UTC, ravishetye approved these changes

2020-04-16 06:36 UTC, merged