Move collaborators roleBinding deleteion logic from MDB to UAC
VertaAI/modeldb pull request #606
Opened 2020-05-05 13:54 UTC by ad-47

2020-05-06 18:36 UTC, ravishetye requested changes
clean up required, but looks good otherwise

2020-05-06 18:36 UTC, ravishetye commented on backend/src/main/java/ai/verta/modeldb/authservice/AuthServiceChannel.java
> +  private void initCollaboratorServiceStubChannel() {
this would no longer be required?

2020-05-07 04:23 UTC, ad-47 commented on backend/src/main/java/ai/verta/modeldb/authservice/AuthServiceChannel.java
> +  private void initCollaboratorServiceStubChannel() {
Removed

2020-05-08 02:07 UTC, ravishetye approved these changes

2020-05-08 08:00 UTC, ad-47 commented
Wating to approved and merge it first respective UAC PR: https://github.com/VertaAI/verta-uacservice/pull/224

2020-05-08 21:11 UTC, merged