remove unique constraint from liquebase for project & dataset name
VertaAI/modeldb pull request #665
Opened 2020-05-25 07:58 UTC by ad-47

2020-05-26 19:25 UTC, ravishetye commented on backend/src/main/resources/liquibase/db-changelog-1.0.xml
> +            <column name="deleted" type="boolean"/>
why is this change required?

2020-05-26 19:46 UTC, ravishetye requested changes
we will have to drop and recreate the index, since this will now modify the index already created.
we will have to do it in a new changeset

2020-05-27 04:17 UTC, ad-47 commented
Updated indexes as per review comment

2020-05-28 18:15 UTC, ravishetye commented
can you pull in master, I do not expect so many changes

2020-05-29 05:30 UTC, ravishetye approved these changes

2020-05-29 05:30 UTC, merged