(Proto) Remove returns from the requests
VertaAI/modeldb pull request #673
Opened 2020-05-27 07:37 UTC by ad-47

2020-05-27 16:58 UTC, convoliution requested changes
I think we should return an empty response (like we do [in `VersioningService`](https://github.com/VertaAI/modeldb/blob/master/protos/protos/public/modeldb/versioning/VersioningService.proto#L216)) instead of introducing `google/protobuf/empty.proto`.

It looks to me like `google/protobuf/empty.proto` causes problems during Swagger generation.
```
Processing ../../protos/gen/swagger/protos/public/modeldb/ExperimentRunService.swagger.json
Traceback (most recent call last):
  File "../tools/swagger_codegen.py", line 297, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "../tools/swagger_codegen.py", line 43, in main
    create_api(result_dir, result_package, api_name, content, templates, file_suffix, case)
  File "../tools/swagger_codegen.py", line 95, in create_api
    success_response = resolve_type(definition)
  File "../tools/swagger_codegen.py", line 239, in resolve_type
    return resolve_type(typedef['schema'])
  File "../tools/swagger_codegen.py", line 241, in resolve_type
    if typedef['type'] == 'string':
KeyError: 'type'
```

2020-05-27 17:50 UTC, convoliution commented
Adding John as a reviewer so frontend has visibility on this change

2020-05-28 17:07 UTC, convoliution approved these changes
Looks good to me. @kirillGulyaev has also confirmed that the WebApp will be fine, as well.

2020-05-29 03:17 UTC, ravishetye requested changes

2020-05-29 03:17 UTC, ravishetye commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
revert

2020-05-29 03:17 UTC, ravishetye commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
revert

2020-05-29 03:17 UTC, ravishetye commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
revert

2020-05-29 03:17 UTC, ravishetye commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
revert

2020-05-29 03:17 UTC, ravishetye commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
revert

2020-05-29 06:09 UTC, ad-47 commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
Done

2020-05-29 06:10 UTC, ad-47 commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
Done

2020-05-29 06:10 UTC, ad-47 commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
Done

2020-05-29 06:10 UTC, ad-47 commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
Done

2020-05-29 06:10 UTC, ad-47 commented on protos/protos/public/modeldb/ExperimentRunService.proto
> -        ExperimentRun experiment_run = 1;
Done

2020-06-01 02:05 UTC, ravishetye approved these changes

2020-06-01 02:05 UTC, merged