protos for the get versioned blob presigned url
VertaAI/modeldb pull request #702
Opened 2020-06-02 11:45 UTC by ad-47

2020-06-02 23:21 UTC, convoliution commented on protos/protos/public/modeldb/versioning/VersioningService.proto
> +
This also needs `uint64 part_number` [for multipart upload](https://github.com/VertaAI/modeldb/blob/f3540fc7378f8690e3331275a690c4fa90e42a38/protos/protos/public/modeldb/CommonService.proto#L111) (see Slack thread)

2020-06-02 23:21 UTC, convoliution requested changes

2020-06-02 23:21 UTC, convoliution commented on protos/protos/public/modeldb/versioning/VersioningService.proto
> +
This needs `uint64 part_number` [for multipart upload](https://github.com/VertaAI/modeldb/blob/f3540fc7378f8690e3331275a690c4fa90e42a38/protos/protos/public/modeldb/CommonService.proto#L111) (see Slack thread)

2020-06-03 13:41 UTC, ad-47 commented
Added endpoints for VersionedBlobArtifact multipart upload

2020-06-03 15:34 UTC, convoliution approved these changes

2020-06-04 04:30 UTC, ravishetye approved these changes

2020-06-04 04:41 UTC, merged