VR-4582 dataset blobs description metadata proto
VertaAI/modeldb pull request #739
Opened 2020-06-09 09:06 UTC by evgeniilezhnin

2020-06-10 05:34 UTC, ravishetye requested changes
this will change based on the implementation PR, we could use the VersioningCompositeIdentifier to attach label or description to it. So we need to add 3 more APIs for add,get,delete description

2020-06-10 08:49 UTC, evgeniilezhnin commented
> this will change based on the implementation PR, we could use the VersioningCompositeIdentifier to attach label or description to it. So we need to add 3 more APIs for add,get,delete description

created separate endpoints for metadata parameters instead of labels (this will be used only for description parameter for now)

2020-06-10 22:47 UTC, ravishetye commented on protos/protos/public/modeldb/metadata/MetadataService.proto
> +message GetParameterRequest {
replace Parametere with Metadata and theen this looks good to me.

2020-06-11 01:29 UTC, ravishetye commented on protos/protos/public/modeldb/metadata/MetadataService.proto
> +message GetParameterRequest {
or `Property` to avoid the repetition of metadata/metadata

2020-06-11 01:30 UTC, ravishetye commented on protos/protos/public/modeldb/metadata/MetadataService.proto
> +message GetParameterRequest {
feel free to merge this is you end up making the change

2020-06-11 06:22 UTC, merged