Use cache for more fields of experiment run
VertaAI/modeldb pull request #987
Opened 2020-07-14 02:51 UTC by conradoverta

2020-07-14 23:15 UTC, convoliution commented on client/verta/verta/_tracking/experimentrun.py
> +        self._clear_cache()
```suggestion
        self._refresh_cache()
```

2020-07-14 23:16 UTC, convoliution requested changes

2020-07-14 23:16 UTC, convoliution commented on client/verta/verta/_tracking/experimentrun.py
> +        self._clear_cache()
```suggestion
        self._refresh_cache()
```

2020-07-14 23:41 UTC, convoliution commented
I noticed that the `get_tags()` test fails (returns fewer items than expected). Need to check if it's a quirk of the test or caching tags.

2020-07-16 01:19 UTC, conradoverta commented
> I noticed that the `get_tags()` test fails (returns fewer items than expected). Need to check if it's a quirk of the test or caching tags.

This is weird =)

2021-11-22 12:29 UTC, closed without merging